// Date: 3/12/2014 5:59:51 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package comdotgame.com.search;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBrockCentrifuge extends ModelBase
{
  //fields
    ModelRenderer CentrifugeBase;
    ModelRenderer CentrifugePole;
    ModelRenderer CentrifugeHolder;
    ModelRenderer Vial1;
    ModelRenderer Vial2;
    ModelRenderer Vial3;
    ModelRenderer Vial4;
    ModelRenderer CentrifugeSide1;
    public ModelRenderer CentrifugeSide2;
    ModelRenderer CentrifugeSide3;
    ModelRenderer CentrifugeSide4;
    ModelRenderer CentrifugeTop;
  
  public ModelBrockCentrifuge()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      CentrifugeBase = new ModelRenderer(this, 92, 0);
      CentrifugeBase.addBox(0F, 0F, 0F, 16, 2, 16);
      CentrifugeBase.setRotationPoint(-8F, 22F, -8F);
      CentrifugeBase.setTextureSize(256, 128);
      CentrifugeBase.mirror = true;
      setRotation(CentrifugeBase, 0F, 0F, 0F);
      CentrifugePole = new ModelRenderer(this, 1, 36);
      CentrifugePole.addBox(0F, 0F, 0F, 4, 10, 4);
      CentrifugePole.setRotationPoint(-2F, 12F, -2F);
      CentrifugePole.setTextureSize(256, 128);
      CentrifugePole.mirror = true;
      setRotation(CentrifugePole, 0F, 0F, -0.0174533F);
      CentrifugeHolder = new ModelRenderer(this, 0, 59);
      CentrifugeHolder.addBox(0F, 0F, 0F, 10, 1, 10);
      CentrifugeHolder.setRotationPoint(-5F, 11F, -5F);
      CentrifugeHolder.setTextureSize(256, 128);
      CentrifugeHolder.mirror = true;
      setRotation(CentrifugeHolder, 0F, 0F, 0F);
      Vial1 = new ModelRenderer(this, 0, 0);
      Vial1.addBox(-0.5F, -0.5F, -0.5F, 1, 3, 1);
      Vial1.setRotationPoint(-3F, 10F, 3F);
      Vial1.setTextureSize(256, 128);
      Vial1.mirror = true;
      setRotation(Vial1, 0.8726646F, -0.8726646F, 0F);
      Vial2 = new ModelRenderer(this, 0, 0);
      Vial2.addBox(-0.5F, 0F, 0.5F, 1, 3, 1);
      Vial2.setRotationPoint(2F, 10F, 2F);
      Vial2.setTextureSize(256, 128);
      Vial2.mirror = true;
      setRotation(Vial2, 0.8726646F, 0.8726646F, 0F);
      Vial3 = new ModelRenderer(this, 0, 0);
      Vial3.addBox(-0.5F, -0.5F, -0.5F, 1, 3, 1);
      Vial3.setRotationPoint(-3F, 10F, -3F);
      Vial3.setTextureSize(256, 128);
      Vial3.mirror = true;
      setRotation(Vial3, -0.8726646F, 0.8726646F, 0F);
      Vial4 = new ModelRenderer(this, 0, 0);
      Vial4.addBox(-0.5F, -0.5F, -0.5F, 1, 3, 1);
      Vial4.setRotationPoint(3F, 10F, -3F);
      Vial4.setTextureSize(256, 128);
      Vial4.mirror = true;
      setRotation(Vial4, -0.8726646F, -0.8726646F, 0F);
      CentrifugeSide1 = new ModelRenderer(this, 64, 0);
      CentrifugeSide1.addBox(0F, 0F, 0F, 1, 8, 12);
      CentrifugeSide1.setRotationPoint(-6F, 4F, -6F);
      CentrifugeSide1.setTextureSize(256, 128);
      CentrifugeSide1.mirror = true;
      setRotation(CentrifugeSide1, 0F, 0F, 0F);
      CentrifugeSide2 = new ModelRenderer(this, 0, 111);
      CentrifugeSide2.addBox(0F, 0F, 0F, 10, 7, 1);
      CentrifugeSide2.setRotationPoint(-5F, 5F, 5F);
      CentrifugeSide2.setTextureSize(256, 128);
      CentrifugeSide2.mirror = true;
      setRotation(CentrifugeSide2, 0F, 0F, 0F);
      CentrifugeSide3 = new ModelRenderer(this, 64, 0);
      CentrifugeSide3.addBox(0F, 0F, 0F, 1, 8, 12);
      CentrifugeSide3.setRotationPoint(5F, 4F, -6F);
      CentrifugeSide3.setTextureSize(256, 128);
      CentrifugeSide3.mirror = true;
      setRotation(CentrifugeSide3, 0F, 0F, 0F);
      CentrifugeSide4 = new ModelRenderer(this, 0, 95);
      CentrifugeSide4.addBox(0F, 0F, 0F, 10, 7, 1);
      CentrifugeSide4.setRotationPoint(-5F, 5F, -6F);
      CentrifugeSide4.setTextureSize(256, 128);
      CentrifugeSide4.mirror = true;
      setRotation(CentrifugeSide4, 0F, 0F, 0F);
      CentrifugeTop = new ModelRenderer(this, 0, 18);
      CentrifugeTop.mirror = true;
      CentrifugeTop.addBox(0F, 0F, 0F, 10, 1, 12);
      CentrifugeTop.setRotationPoint(-5F, 4F, -6F);
      CentrifugeTop.setTextureSize(256, 128);
      CentrifugeTop.mirror = true;
      setRotation(CentrifugeTop, 0F, 0F, 0F);
      CentrifugeTop.mirror = false;
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    CentrifugeBase.render(f5);
    CentrifugePole.render(f5);
    CentrifugeHolder.render(f5);
    Vial1.render(f5);
    Vial2.render(f5);
    Vial3.render(f5);
    Vial4.render(f5);
    CentrifugeSide1.render(f5);
    CentrifugeSide2.render(f5);
    CentrifugeSide3.render(f5);
    CentrifugeSide4.render(f5);
    CentrifugeTop.render(f5);
  }
  
  public void renderBase(float f5)
  {
	CentrifugeBase.render(f5);
	CentrifugePole.render(f5);
  }
  
  public void renderTop(float f5)
  {
	CentrifugeHolder.render(f5);
	Vial1.render(f5);
	Vial2.render(f5);
	Vial3.render(f5);
	Vial4.render(f5);
	CentrifugeSide1.render(f5);
	CentrifugeSide2.render(f5);
	CentrifugeSide3.render(f5);
	CentrifugeSide4.render(f5);
	CentrifugeTop.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
